import React from 'react';
import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';
import NavBar from './components/NavBar';
import './globals.css';

const urbanist = Urbanist({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body className={urbanist.className}>
      <NavBar />
      {children}
    </body>
  </html>
);

export default RootLayout;
